schemas:
  bootstrap: 8000
  dstheme: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'https://des1.lndo.site:4433/themes/contrib/dstheme/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
table_responsive: '-1'
table: ''
